# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('height', models.CharField(max_length=255, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('result', models.CharField(max_length=255, null=True)),
                ('score', models.IntegerField(null=True)),
                ('units', models.CharField(max_length=255, null=True)),
                ('mods', models.CharField(max_length=255, null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('results_best', models.CharField(max_length=255, null=True)),
                ('results_worst', models.CharField(max_length=255, null=True)),
                ('results_avg', models.CharField(max_length=255, null=True)),
                ('results_best_male', models.CharField(max_length=255, null=True)),
                ('results_worst_male', models.CharField(max_length=255, null=True)),
                ('results_avg_male', models.CharField(max_length=255, null=True)),
                ('results_best_female', models.CharField(max_length=255, null=True)),
                ('results_worst_female', models.CharField(max_length=255, null=True)),
                ('results_avg_female', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.User'),
        ),
        migrations.AddField(
            model_name='result',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.Workout'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.Workout'),
        ),
    ]
