# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exercise',
        ),
        migrations.AddField(
            model_name='comment',
            name='routine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='routine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine'),
        ),
    ]
