# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20160908_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine'),
        ),
    ]
