# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20160908_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.User')),
            ],
        ),
    ]
