# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20160915_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='workouts.User'),
        ),
        migrations.AddField(
            model_name='follower',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workouts.User'),
        ),
    ]
