# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20160916_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='f',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='u',
            new_name='user',
        ),
    ]
