# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20160916_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.User')),
            ],
        ),
    ]
