# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_user_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='routine',
        ),
        migrations.AddField(
            model_name='comment_routine',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Comment'),
        ),
        migrations.AddField(
            model_name='comment_routine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine'),
        ),
    ]
