# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_auto_20161013_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=70)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine')),
            ],
        ),
    ]
