# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_auto_20161014_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
