# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_auto_20161014_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=1000),
        ),
    ]
